apiVersion: apps/v1
kind: Deployment
metadata:
  name: celerybeat-deployment
  labels:
    app: celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celerybeat
  template:
    metadata:
      labels:
        app: celerybeat
    spec:
      containers:
      - name: celerybeat
        image: "quay.io/hyperkineticnerd/defectdojo-django:latest"
        cmd: ['/wait-for-it.sh', 'mysql.defectdojo.svc:3306', '-t', '30', '--', '/entrypoint-celery-beat.sh']
        envFrom:
        - secretRef:
            name: defectdojo
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
