apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeryworker-deployment
  labels:
    app: celeryworker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: celeryworker
  template:
    metadata:
      labels:
        app: celeryworker
    spec:
      containers:
      - name: celeryworker
        image: "defectdojo/defectdojo-django:latest"
        cmd: ['/wait-for-it.sh', 'mysql.defectdojo.svc:3306', '-t', '30', '--', '/entrypoint-celery-worker.sh']
        env:
        - name: DD_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DATABASE_URL
        - name: DD_CELERY_BROKER_USER
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_CELERY_BROKER_USER
        - name: DD_CELERY_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_CELERY_BROKER_PASSWORD
        - name: DD_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_SECRET_KEY
        - name: DD_CREDENTIAL_AES_256_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_CREDENTIAL_AES_256_KEY
        volumeMounts:
        - name: defectdojo-media
          mountPath: /app/media
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: defectdojo-media
        emptyDir: {}
