apiVersion: v1
kind: Service
metadata:
  name: celery-beat
  labels:
    app: defectdojo
    defectdojo.org/component: celery-beat
spec:
  ports:
  - port: 3031
    name: uwsgi
  clusterIP: None
  selector:
    defectdojo.org/component: celery-beat
