apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeryworker-deployment
  labels:
    app: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celeryworker
  template:
    metadata:
      labels:
        app: celeryworker
    spec:
      volumes:
      - name: defectdojo-media
        emptyDir: {}
      containers:
      - name: celeryworker
        image: "quay.io/hyperkineticnerd/defectdojo-django:latest"
        cmd: ['/wait-for-it.sh', 'mysql.defectdojo.svc:3306', '-t', '30', '--', '/entrypoint-celery-worker.sh']
        envFrom:
        - secretRef:
            name: defectdojo
        volumeMounts:
        - name: defectdojo-media
          mountPath: /app/media
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
