apiVersion: apps/v1
kind: Deployment
metadata:
  name: defectdojo-deployment
  labels:
    app: defectdojo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: defectdojo
  template:
    metadata:
      labels:
        app: defectdojo
    spec:
      initContainers:
      - name: defectdojo-init
        image: "defectdojo/defectdojo-django:latest"
        cmd: ['/wait-for-it.sh', 'mysql:3306', '--', '/entrypoint-initializer.sh']
        env:
        - name: DD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_ADMIN_USER
        - name: DD_ADMIN_MAIL
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_ADMIN_MAIL
        - name: DD_ADMIN_FIRST_NAME
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_ADMIN_FIRST_NAME
        - name: DD_ADMIN_LAST_NAME
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_ADMIN_LAST_NAME
        - name: DD_INITIALIZE
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_INITIALIZE
        - name: DD_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DATABASE_URL
        - name: DD_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_SECRET_KEY
        - name: DD_CREDENTIAL_AES_256_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_CREDENTIAL_AES_256_KEY
      containers:
      - name: uwsgi
        image: "defectdojo/defectdojo-django:latest"
        cmd: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', '/entrypoint-uwsgi.sh']
        env:
        - name: DD_DEBUG
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DEBUG
        - name: DD_DJANGO_METRICS_ENABLED
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DJANGO_METRICS_ENABLED
        - name: DD_ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_ALLOWED_HOSTS
        - name: DD_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DATABASE_URL
        - name: DD_CELERY_BROKER_USER
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DATABASE_URL
        - name: DD_CELERY_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_DATABASE_URL
        - name: DD_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_SECRET_KEY
        - name: DD_CREDENTIAL_AES_256_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_CREDENTIAL_AES_256_KEY
        ports:
        - containerPort: 3031
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
          - name: defectdojo-media
            mountPath: /app/media
      volumes:
        - name: defectdojo-media
          emptyDir: {}
