apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: defectdojo
spec:
  host: defectdojo-defectdojo.apps.dev.ocp4.hkn.lab 
  port:
    targetPort: http
  termination: edge
  to:
    kind: Service
    name: nginx
