MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:defectdojo@mysql:3306/defectdojo}"
MYSQL_USER: "${DD_DATABASE_USER:-defectdojo}"
MYSQL_PASSWORD: "${DD_DATABASE_PASSWORD:-defectdojo}"
MYSQL_DATABASE: "${DD_DATABASE_NAME:-defectdojo}"
