apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
stringData:
  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  MYSQL_USER: "defectdojo"
  MYSQL_PASSWORD: "defectdojo"
  MYSQL_DATABASE: "defectdojo"
