image: mysql:5.7.36@sha256:7a3a7b7a29e6fbff433c339fc52245435fa2c308586481f2f92ab1df239d6a29
environment:
  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  DD_DATABASE_URL: "${DD_DATABASE_URL:-mysql://defectdojo:defectdojo@mysql:3306/defectdojo}"
  MYSQL_USER: "${DD_DATABASE_USER:-defectdojo}"
  MYSQL_PASSWORD: "${DD_DATABASE_PASSWORD:-defectdojo}"
  MYSQL_DATABASE: "${DD_DATABASE_NAME:-defectdojo}"
command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
    - defectdojo_data:/var/lib/mysql
