image: "defectdojo/defectdojo-nginx:${NGINX_VERSION:-latest}"
depends_on:
  - uwsgi
environment:
  NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}"
volumes:
  - defectdojo_media:/usr/share/nginx/html/media
ports:
  - target: 8080
    published: ${DD_PORT:-8080}
    protocol: tcp
    mode: host
  - target: 8443
    published: ${DD_TLS_PORT:-8443}
    protocol: tcp
    mode: host
