apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: defectdojo
    defectdojo.org/component: nginx
spec:
  ports:
  - name: http
    port: 8080
  - name: uwsgi
    port: 3031
  clusterIP: None
  selector:
    app: defectdojo
    defectdojo.org/component: nginx
