# This docker-compose.yml file  is fully functional to evaluate DefectDojo
# in your local environment.
#
# Although Docker Compose is one of the supported installation methods to
# deploy a containerized DefectDojo in a production environment, the
# docker-compose.yml file is not intended for production use without first
# customizing it to your particular situation.
---
version: '3.7'
services:
  nginx:
    image: "quay.io/hyperkineticnerd/defectdojo-nginx:${NGINX_VERSION:-latest}"
  uwsgi:
    image: "quay.io/hyperkineticnerd/defectdojo-django:${DJANGO_VERSION:-latest}"
  celerybeat:
    image: "quay.io/hyperkineticnerd/defectdojo-django:${DJANGO_VERSION:-latest}"
  celeryworker:
    image: "quay.io/hyperkineticnerd/defectdojo-django:${DJANGO_VERSION:-latest}"
  initializer:
    image: "quay.io/hyperkineticnerd/defectdojo-django:${DJANGO_VERSION:-latest}"
